language: python
os: 
    - linux

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install codecov

script:
    - coverage run -m unittest discover

after_success:
    - codecov



